### ISSUE TITLE
Release symphony-java-client version 0.9.0

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#10]
The release process is implemented and documented in https://github.com/symphonyoss/ssf-parent-pom ; from version `2`, the Parent Pom includes all docs and configurations to configure your workstation to run a release.

All legal and security criteria are matched, so there's no red flag that stops us from releasing; as such, I'd like to propose a (first) release of symphony-java-client, version 0.9.0

The only blocking issue right now is #9 , working on it now.

@ftbb, would you like to be the Release Manager of the symphony-java-client, at least for now?

**Comment by ftbb** [comment]
@maoo yes.  Think its best right now, but we should have at least two contributors that have the authority in the end.
