### ISSUE TITLE
Unhandled Exception in AuthRefreshTask

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-java-client#112]
If AuthRefreshTask fails in anything except a NetworkException, it will cause the timer thread that runs it to die, and the exception won't be logged.  

This seems to have happened to me (we sometimes have poor network connectivity to Symphony), and the tokens didn't refresh.

thanks,
Rob

**Comment by ftbb** [comment]
commit 2672600208281341d81cc6f54a0911a3cba70c83

This is now fixed and tested (unplugged network). 

SNAPSHOT 1.1.5 published
