### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by kinkoi** [symphonyoss/symphony-java-client#12]
Hi @maoo, I 'm getting the following error after sync to 0962933a57bd512c0e4fcf4a8c2c81ee5572a346. 

[INFO] --- maven-dependency-plugin:2.10:unpack (unpack) @ symphony-agent-java-jersey2-client ---
[INFO] Configured Artifact: org.symphonyoss.symphony:symphony-agent-api:0.9.0-SNAPSHOT:jar
[INFO] Unpacking /Users/kinkoi.lo/dev/bot/sym-java-origin/symphony-apis/agent/api/target/classes to /Users/kinkoi.lo/dev/bot/sym-java-origin/symphony-apis/agent/java-jersey2-client/target/generated-sources/api with includes "" and excludes ""
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Symphony Java Client ............................... SUCCESS [  0.789 s]
[INFO] Symphony Apis ...................................... SUCCESS [  0.070 s]
[INFO] Symphony Agent Service ............................. SUCCESS [  0.074 s]
[INFO] Symphony Agent Service API ......................... SUCCESS [  1.449 s]
[INFO] Symphony Agent Service Java Client ................. FAILURE [  0.506 s]
[INFO] Symphony Authenticator Service ..................... SKIPPED
[INFO] Symphony Authenticator Service API ................. SKIPPED
[INFO] Symphony Authenticator Service Java Client ......... SKIPPED
[INFO] Symphony POD Service ............................... SKIPPED
[INFO] Symphony POD Service API ........................... SKIPPED
[INFO] Symphony POD Service Java Client ................... SKIPPED
[INFO] Symphony Client .................................... SKIPPED
[INFO] Symphony Client Examples ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.169 s
[INFO] Finished at: 2016-07-30T08:21:02-07:00
[INFO] Final Memory: 25M/449M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "artifactory" could not be activated because it does not exist.
[WARNING] The requested profile "Symphony" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (unpack) on project symphony-agent-java-jersey2-client: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :symphony-agent-java-jersey2-client

**Comment by maoo** [comment]
Hi @kinkoi , can you please tell me which command you're running and which branch? Right now the build is green on all branches - https://travis-ci.org/symphonyoss/symphony-java-client/branches

**Comment by kinkoi** [comment]
Oh, it failed when I did "mvn compile"; it is working for me now when I used "mvn package".

**Comment by maoo** [comment]
Just tried to
```
rm -rf ~/.m2/repository/org/symphonyoss
mvn compile
```
and everything works as expected.
If you see any similar issues, can you grab all the maven logs (from command to last line) and put it in a gist.github.com ? This way I can try to understand what is going on.

Thanks!

**Comment by dannychan** [comment]
@maoo I also see this issue.
https://gist.github.com/dannychan/1e297e40e9dc760d9542f9eedd953074

**Comment by maoo** [comment]
Thanks for the feedback @dannychan ; the 1.8 compiler/target is [set by the ssf-parent-pom](https://github.com/symphonyoss/ssf-parent-pom/blob/master/pom.xml#L136-L137); wondering if it should be lower, considering it's a default value.

The symphony-java-client could (and should) override those property (in the root pom.xml) and set it to 1.7, if it is supposed to work with Java 7 (or any lower version); I'll do some tests locally and keep you posted.

For now, the workaround is to use Java 8.

**Comment by ftbb** [comment]
The symphony-java-client requires java 8, so by default we need make sure that the effective pom has min requirement of 1.8.

  <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>...</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>

or

<properties>
   <maven.compiler.source>1.8</maven.compiler.source>
   <maven.compiler.target>1.8</maven.compiler.target>
</properties>

This should be added to the symphony-java-client and tested.

**Comment by maoo** [comment]
Thanks @ftbb ; those settings are already inherited by ssf-parent-pom:
 https://github.com/symphonyoss/ssf-parent-pom/blob/master/pom.xml#L136-L137

You can validate it by running `mvn help:effective-pom`

I'd rather suggest to add the following to the symphony-java-client (or maybe the ssf-parent-pom, making the JDK version parametric with a Maven property), so that the failure error - if not using Java 8 for compilation - gets clearer:

```
...
<requireJavaVersion>
  <version>1.8.0</version>
</requireJavaVersion>
...
```

More info on http://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html

I can work on it and submit a PR.

**Comment by ftbb** [comment]
commit 25ce0b5d6a749bd3d1b5bd77b486d2c4bca0b98a
Added suggested recommendation.
