### ISSUE TITLE
Publish Javadoc for each release

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#13]
It would be awesome if the Javadoc for this project (including for the swagger-generated code) was generated for each release and published.  Ideally the publishing platform would be Github - [Maven plugins exist to automate this workflow](https://github.com/stephenc/wagon-gitsite).

**Comment by ftbb** [comment]
I believe you will need to create a repository under symphonyoss called **symphonyoss.github.io** in order for documentation to be published to github pages (under master or gh-pages).

For now I am manually publishing to my user pages [API Docs](https://ftbb.github.io/symphony-java-client)  Note: This is a manual process and not integrated with travis build.

**Comment by maoo** [comment]
Discussion followed up on https://symphonyoss.atlassian.net/browse/INFRA-60 ; Javadocs are currently published on http://symphonyoss.github.io/symphony-java-client/

**Comment by maoo** [comment]
Fixed.

Docs are now published on http://symphonyoss.github.io/symphony-java-client/ and are fetched from https://github.com/symphonyoss/symphony-java-client/tree/gh-pages

**Comment by maoo** [comment]
Actually,

the scope of this issue is wider, as it includes publishing automation during build. For this, we can introduce https://github.com/github/maven-plugins on the parent pom.

I'll be working on this and keep you posted.

**Comment by maoo** [comment]
This issue is currently on hold, waiting for https://github.com/symphonyoss/symphony-java-client/issues/43 to be completed

**Comment by ftbb** [comment]
Content from current wiki ( https://github.com/symphonyoss/symphony-java-client/wiki ) will be migrated.
