### ISSUE TITLE
symphony-java-client community activity

### ISSUE THREAD

**Issue by mcleo-d** [symphonyoss/symphony-java-client#136]
As part of the FINOS project lifecycle work happening with the Symphony PMC, this project has been given an INCUBATING status due to the projects close relationship with [symphony-java-api](https://github.com/symphonyoss/symphony-java-api). 

So an informed decision is made by the Symphony PMC whether to ARCHIVE this project, can active contributors to this repository register themselves with a 👍 to best inform the Symphony PMC's decision to ARCHIVE.

Thank you.

**Comment by brooklynrob** [comment]
As @mcleo-d includes and mentions above, it's the [activation criteria](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation), https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation, that should be used as the basis for consideration when voting to move the project to ACTIVE status.

**Comment by mindthegab** [comment]
This project was activated long ago. Here is the link to the PASSED activation [VOTE]:

https://groups.google.com/a/finos.org/forum/?nomobile=true#!search/Esco$20symphony-java-client$20activation/esco-private/5hee96h67XI/PlUw1Z2fDwAJ

The real question for me is whether this project should be archived given:

1. Doesn’t seem to be actively developed (/cc @ftbb)

2. There’s another Java API client actively maintained by symphony at https://github.com/SymphonyPlatformSolutions/symphony-api-client-java which arguably consumers should prefer (@mcleo-d  please check with Vinay).

@mcleo-d worth probably updating the title and text of this issue / request.

**Comment by mcleo-d** [comment]
Hi @mindthegab,

Thank you for providing a link to the project's activation. 

Due to the process that's already been followed, I have reworded the issue to invite the community to register their activity with a 👍 so the final decision to archive is well informed by the Symphony PMC. 

Yours and @brooklynrob's insights are deeply appreciated.

James.

**Comment by pmonks** [comment]
Note that this project has a number of downstream consumers (some of which are themselves are in ACTIVE status).

**Comment by mcleo-d** [comment]
@pmonks - Thank you for demonstrating community activity on this repo. [Based on the evidence provided by @mindthegab](https://github.com/symphonyoss/symphony-java-client/issues/136#issuecomment-568518042), I have raised a PR to set this project to ACTIVE and will notify the Symphony PMC accordingly.

Kind regards,

James.
