### ISSUE TITLE
Suggestion: rename RoomService.removeRoomServiceListener to deregisterRoomServiceListener

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#19]
This is just a suggestion, but for consistency it might be worth renaming `RoomService.removeRoomServiceListener` to `RoomService.deregisterRoomServiceListener` (the registration method is called `registerRoomServiceListener`, and "deregister" is the antonym for "register").

**Comment by pmonks** [comment]
Also, this pattern occurs elsewhere too e.g. `MessageService.removeMessageListener` and `MessageService.removeRoomListener`.

**Comment by ftbb** [comment]
Although I agree that the antonym is "deregister", I would suggest we changing register#Listener to add#Listener for all?   

This would mean we would have simple add#Listener and remove#Listener.

What do you think?

**Comment by pmonks** [comment]
SGTM!

**Comment by ftbb** [comment]
commit 0a491901c6221f4712a72b99f90a1012062ea06e

Deprecated register methods in favor of addListener.

Deployed snapshot.
