### ISSUE TITLE
Parse results from Sonarqube.com

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#2]
https://sonarqube.com/component_issues/index?id=org.symphonyoss%3Asymphony-java-client#resolved=false

**Comment by ftbb** [comment]
Cool @maoo .  Most are related to Exceptions management which we have a github issue on.

All good and we need to work on it.

**Comment by ftbb** [comment]
Commit 161596105b93035ea7902ae7cf90f072e249d87e
Knocked off 250 issues.

Will continue to scrub..

**Comment by ftbb** [comment]
Have excluded generated code for now to focus on core code.
commit 25ce0b5d6a749bd3d1b5bd77b486d2c4bca0b98a

We are driving it down to very few errors now.  More to come.

**Comment by maoo** [comment]
Closing this issue, as there are no bugs/vulnerabilities found on Sonar anymore - https://sonarqube.com/dashboard/index?id=org.symphonyoss.symphony%3Asymphony-java-client

Thanks @ftbb
