### ISSUE TITLE
Exception information is being lost

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#22]
The following pattern appears in many places in the code, and unfortunately it results in some exception information (stack trace segments, specifically) being lost:

```
        ...
        } catch (ApiException e) {
            throw new MessagesException("Failed to send message to stream: " + stream.getId(), e.getCause());
        }
        ...
```
(example from [MessagesClientImpl.java:106](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/symphony/clients/impl/MessagesClientImpl.java#L106))

It would be preferable if all occurrences of this pattern instead preserved the entire root cause exception, as follows:

```
        ...
        } catch (ApiException e) {
            throw new MessagesException("Failed to send message to stream: " + stream.getId(), e);
        }
        ...
```

This ensures that all of the caught exception's information is preserved, while still allowing the type of the exception to be narrowed to the desired type (in this example `MessagesException`).

**Comment by ftbb** [comment]
commit bcb95c94fbdadea1fd911784e40367f78cb239d2
Changed to full stack trace.
