### ISSUE TITLE
Create TrustStore on Windows

### ISSUE THREAD

**Issue by Active** [symphonyoss/symphony-java-client#26]
Hello,

I would like to make a bot, my local symphony admin gave me the p12,
and told me to create the TrustStore, however after few attempts I wasn't
successful. I am looking for help and I believe making the information
public here, would make it easier for future dev.

TL;DR: I am looking for information on how to create a TrustStore on Windows.

Thanks

**Comment by ftbb** [comment]
You should use the JDK **keytool** to create a **truststore** on Windows.

For clarity, the truststore holds certificates (usually root or intermediate) that are used to verify the server certificates of the systems the BOT will be connecting to.   This would include POD, KeyManager/SessionManager and Agent server host systems.   This is especially important when the certs are self signed... 

First, obtain/retrieve the certificates for each of the host systems you are connecting to. 

Second load them into a truststore using the keytool

`keytool -import -file (a cert file) -alias (a name) -keystore (trustStore file name)`

note:  keytool might not be in the windows path, so search for it under Program Files.

Repeat above for all certs... and that's about it.
