### ISSUE TITLE
Getting Compile errors while running through Eclipse

### ISSUE THREAD

**Issue by opolyo01** [symphonyoss/symphony-java-client#27]
I imported a project from parent pom into Eclipse, but getting bunch of compile errors when right click Run As "Maven Install".  

I am not sure if Eclipse inherits my console Java SDK and Maven Version, but here's this info bellow:

am-chpolyakov01:symphony-java-client opolyako$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /Users/opolyako/apache-maven-3.3.9
Java version: 1.8.0_73, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
am-chpolyakov01:symphony-java-client opolyako$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
am-chpolyakov01:symphony-java-client opolyako$ 

Constructing Javadoc information...
1 error
5 warnings
[ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.api
javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.invoker
javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.invoker.auth
javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.model
javadoc: warning - No source files for package src.test.java.org.symphonyoss.symphony.pod.api
javadoc: error - No public or protected classes found to document.

Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/../bin/javadoc @options @packages

Refer to the generated Javadoc files in '/Users/opolyako/tutorials/symphony-java-client/symphony-apis/pod/java-jersey2-client/target/apidocs' dir.

org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.api
javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.invoker
javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.invoker.auth
javadoc: warning - No source files for package src.main.java.org.symphonyoss.symphony.pod.model
javadoc: warning - No source files for package src.test.java.org.symphonyoss.symphony.pod.api
javadoc: error - No public or protected classes found to document.

Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/../bin/javadoc @options @packages

Refer to the generated Javadoc files in '/Users/opolyako/tutorials/symphony-java-client/symphony-apis/pod/java-jersey2-client/target/apidocs' dir.

```
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5188)
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2075)
at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:188)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

[INFO] Building jar: /Users/opolyako/tutorials/symphony-java-client/symphony-apis/pod/java-jersey2-client/target/symphony-pod-java-jersey2-client-1.0.0-SNAPSHOT-javadoc.jar
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ symphony-pod-java-jersey2-client ---
[WARNING] Rule 3: org.symphonyoss.maven.enforcer.RequirePomMetadataRule failed with message:
RequirePomMetadataRule is failing with the following error: pom.xml is missing <description> element  or it's empty
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.004 s
[INFO] Finished at: 2016-10-14T15:44:41-05:00
[INFO] Final Memory: 43M/516M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (default) on project symphony-pod-java-jersey2-client: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ftbb** [comment]
Just tested fresh master clone without error.

#mvn clean install

Maven 3.x+ and Jdk 1.8+ should work just fine.

Note: might be easier for you to use the public maven dependency.  

 <dependency>
        <groupId>org.symphonyoss.symphony</groupId>
        <artifactId>symphony-client</artifactId>
        <version>0.9.1</version>
    </dependency>

**Comment by opolyo01** [comment]
Yes, it works fine from terminal.  I am just trying to see what am I missing while running through Eclipse or InteliJ?  Where do I put this public maven dependency?  There are bunch of pom.xml files, so not sure which one needs to be updated.
<img width="2314" alt="screen shot 2016-10-14 at 4 39 54 pm" src="https://cloud.githubusercontent.com/assets/558296/19403398/9e25b51c-922c-11e6-8125-ff23a9420126.png">

**Comment by opolyo01** [comment]
<img width="2308" alt="screen shot 2016-10-14 at 4 46 20 pm" src="https://cloud.githubusercontent.com/assets/558296/19403525/838eb644-922d-11e6-85c0-0173b7082fc4.png">

**Comment by ftbb** [comment]
I use IntelliJ to build it...with the same external maven that I run on the command line.  

Honestly doesn't matter..

I will download Eclipse :/  and test it for you...  might be a day or so.

**Comment by ftbb** [comment]
Actually, do me a favor and clone https://github.com/symphonyoss/ssf-parent-pom.git

#mvn clean install  the project.

Then see if it symphony-java-client cleans up..

**Comment by opolyo01** [comment]
am-chpolyakov01:tutorials opolyako$ cd ssf-parent-pom/
am-chpolyakov01:ssf-parent-pom opolyako$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building The Symphony Software Foundation 3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ symphonyoss ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ symphonyoss ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ symphonyoss ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ symphonyoss ---
[INFO] Installing /Users/opolyako/tutorials/ssf-parent-pom/pom.xml to /Users/opolyako/.m2/repository/org/symphonyoss/symphonyoss/3-SNAPSHOT/symphonyoss-3-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.248 s
[INFO] Finished at: 2016-10-14T17:00:48-05:00
[INFO] Final Memory: 14M/309M
[INFO] -----------------------------------------

**Comment by opolyo01** [comment]
After running a build it still gives the same compile errors in Eclipse.  Intelij doesn't seem to give compile errors, but it looks for Android SDK somehow (not sure how to run maven within InteliJ either)

<img width="2312" alt="screen shot 2016-10-14 at 4 59 23 pm" src="https://cloud.githubusercontent.com/assets/558296/19403917/ef41d568-922f-11e6-930e-5407915f3660.png">

**Comment by ftbb** [comment]
I just tried Eclipse...and it continues to be confused.  The core issue is generated code is not identified by other modules in the build.  Still looking into it..

A couple options for now:
1. Use Intellij, and simply ignore the Android framework configuration which is coming through because of swagger-gen source generator. 

2. Using eclipse, run maven to build Symphony-Java-client, but use pom dependency for actual project work.  Would also consider using the publicly available maven central library as dependency.

**Comment by maoo** [comment]
@opolyo01 , are you still having issues with your local environment? If you're looking for the Java Client javadocs, you can now find them on https://symphonyoss.github.io/symphony-java-client/

Please let me know if we can help you further.
