### ISSUE TITLE
Could you add a clean shutdown to the MessageService MessageFeedWorker thread?

### ISSUE THREAD

**Issue by xexuxjy** [symphonyoss/symphony-java-client#28]
Hi.

When a MessageService instance is created, it spins off a separate worker thread for reading messages from the data feed client. There doesn't seem to be a nice way of getting that thread to stop as part of a clean shutdown. Could you consider making it a Daemon thread or providing something like a shutdown call at the SymphonyClient level to pair with the init call that tidies up the thread and so on.

Thanks,

Mark

**Comment by ftbb** [comment]
We are going the SymphonyClient.shutdown() route...there are a few threads we should clean...

Trying to squeeze this into my morning.

**Comment by xexuxjy** [comment]
Great news. Thanks Frank.

**Comment by ftbb** [comment]
On develop branch and Snapshot 1.0.0-SNAPSHOT deployed to maven. 

commit 8fc1f2820eb4d0c7b0eb026b02d7481e063b706b

Tested under ChatExample.

Please close, once you verify. 

Frank

**Comment by xexuxjy** [comment]
Works nicely.

Thanks.
