### ISSUE TITLE
Add NOTICE entries for category B licenses

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#29]
Some dependencies used by the symphony-java-client are licensed with category-B compatible Apache licenses; as such, they should be linked in the NOTICE and README file of the project.

Working on it right now, will produce a PR soon

**Comment by pmonks** [comment]
This can be checked by running `mvn project-info-reports:dependencies` then comparing to the [Apache documentation on compatible licenses](http://www.apache.org/legal/resolved.html).

**Comment by maoo** [comment]
Here's the initial commit; I've run the command @pmonks suggested and manually scanned for non category-a licenses.

Now the question is what we want to mention on the README; strangely, I don't see any note on READMEs of Apache projects; maybe changing the NOTICE file is "prominent" enough?

**Comment by pmonks** [comment]
@copiesofcopies may have some guidance for us on this point, @maoo.

**Comment by maoo** [comment]
Notice file properly defined
