### ISSUE TITLE
SymUser equals method (userId)

### ISSUE THREAD

**Issue by xexuxjy** [symphonyoss/symphony-java-client#30]
SymUser doesn't seem to have an equals method defined (should compare long UserId?) so different instances of the same user can exist in a set, or a set lookup can fail.

**Comment by ftbb** [comment]
commit 0f4aa284c310a6539781bcbd5c09f5006ed7d761

Deployed to 1.0.0-SNAPSHOT

Please verify and close...

**Comment by xexuxjy** [comment]
Equals is there thanks, but hashCode isn't , so that still can have duplicates in a HashSet<SymUser> . I also noticed that ChatService makes use of HashSet<Chat> but Chat only implements equals and not hashCode.

Thanks.

**Comment by ftbb** [comment]
commit fe08f25750233d747000e2c2f7bb8b65e93e8958

SymUser, Chat, Room objects were all updated..

Please verify.

**Comment by xexuxjy** [comment]
HashSet<SymUser> now working as expected. Thanks.
