### ISSUE TITLE
over 1 minute on SymphonyClient.init() call. And similar slow response on other API calls.

### ISSUE THREAD

**Issue by shirleyshan** [symphonyoss/symphony-java-client#32]
The SymphonyClient.init() call takes 70 secs to complete. And something strange is that if the streamsClient().getRoomDetail() is called right after SymphonyClient.init(), the call finishes rather quickly such as in 187 ms. But if streamsClient().getRoomDetail() gets called later again, it takes similar over 70 secs to complete.

Any ideas? Thanks.

**Comment by ftbb** [comment]
Unfortunately what I'm about to say is not going to sound helpful.

It would seem you have one or 

1) A network connectivity issue to one of the URL's...  Test with ping, curl or another tool directly with each.
2) The Agent server is having a performance issue or having a problem connecting to the POD.
3) The client is pulling down all the presence detail upon startup and polling thereafter, so there could be too much data being consumed through the network (congestion) or the java application needs more memory..etc. How many users defined on your network?  Note: I'm going to be putting in a property to disable presence polling soon as per Symphony LLC feedback.

**Comment by ftbb** [comment]
I just tried to send a message to your POD over symphony and it seems to be failing.  I would check with Symphony LLC on health of your system. 

(note: I have tested sending to other external PODs without issue)

**Comment by shirleyshan** [comment]
I am running against Symphony's Foundation-dev server. I have two accounts, one with my company POD server and the other one with Symphony Foundation-dev.

I will rule out 1) since I tested against Symphony foundation-dev server directly and all calls return in the 100 ms range.

For 2),  the call streamClient.getRoomDetail by RoomID should not involve agent server, right?

What puzzled me is that after initializing SymphonyClient, the steamClient.getRoomDetail still takes over 1 minute to complete. But if these two methods are called very closely, the getRoomDetail runs reasonably fast.

**Comment by ftbb** [comment]
Yes, it will call the POD the URL under the hood.   With that said, you can send POD calls through the Agent server as well.  That might be one for @maoo ..

I will test against the foundation POD to make sure there are no issues...

**Comment by ftbb** [comment]
Just tested 5 times to the foundation pod without issue..

-Dsessionauth.url=https://foundation-dev-api.symphony.com/sessionauth
-Dkeyauth.url=https://foundation-dev-api.symphony.com/keyauth
-Dsymphony.agent.pod.url=https://foundation-dev.symphony.com/pod
-Dsymphony.agent.agent.url=https://foundation-dev-api.symphony.com/agent

Can you share code (offline)?

**Comment by shirleyshan** [comment]
I increased tomcat server memory to 2G and 4G, and didn't see any improvements.

**Comment by ftbb** [comment]
It will not be memory issue.. There are very few accounts on foundation POD.  Can you reach out to me over Symphony (foundation-dev POD)?

**Comment by shirleyshan** [comment]
It turned out to be my network issues. Thank Frank for your suggestions.
