### ISSUE TITLE
Room and Chat listener methods are inconsistent

### ISSUE THREAD

**Issue by peterjoel** [symphonyoss/symphony-java-client#34]
To add a listener to a `Chat`, there is `chat.addListener()`, but for a room, it's `room.setRoomListener()`.  These are inconsistently named (including the noun in the method name vs not), and also it means you can add multiple listeners to chats, but only one listener to a room.

**Comment by ftbb** [comment]
Known issue and should be fixed in 1.0.0 soon.   Adding room.addListener()

**Comment by ftbb** [comment]
commit 2e2985374e13e5252120b55dd7567240a5a9e746

Updated develop branch and pushed SNAPSHOT. 

Room setRoomListener / getRoomListener are now deprecated.

Added addListener(RoomListener) and removeListener(RoomListener) which is consistent with other models. 

Updated example code.

Please confirm and close if satisfied.
