### ISSUE TITLE
Move symphony-apis module to separate repository

### ISSUE THREAD

**Issue by ftbb** [symphonyoss/symphony-java-client#40]
The symphony-apis endpoints are currently generated through swagger-gen.  This output is slightly adjusted to resolve swagger deficiencies (Class Hierarchy). 

The view is to move the generation and management of the Java endpoints into a separate manged project.  

This will create the appropriate segmentation between the SDK and endpoints being leveraged.  It also attempts to future proof future implementations of the Symphony REST API.

**Comment by maoo** [comment]
Quick confirmation: when you say "separate managed project" you mean a separate github repository on github.com/symphonyoss , correct?

**Comment by ftbb** [comment]
Correct

**Comment by maoo** [comment]
Ok, I'll create an empty repository with the same permission as this project; do you want to enable Wiki and Issues, or you prefer to keep managing issues here for both projects?

What would be the name of the project, "symphony-apis" or "symphony-java-apis" ? The former could be a bit too generic.

**Comment by ftbb** [comment]
I would suggest "symphony-java-api" as this would be specific to java bindings.  The "symphony-java-client" will be more focused on higher level functions and services (more an SDK really).

**Comment by maoo** [comment]
Done - https://github.com/symphonyoss/symphony-java-api

@ftbb is Admin
@A-Joshi has Write permission

Feel free to check and close this issue.

**Comment by ftbb** [comment]
I would add @blackrock-engineering to it as well.

**Comment by maoo** [comment]
Done.
