### ISSUE TITLE
Move symphony-client-examples module to symphony-java-sample-bots project

### ISSUE THREAD

**Issue by ftbb** [symphonyoss/symphony-java-client#41]
In an effort to simplify development of the java-client and combine existing project work, the symphony-client-examples module will be moved and incorporated with the project [symphony-java-sample-bots](https://github.com/symphonyoss/symphony-java-sample-bots) project.

**Comment by maoo** [comment]
Move is done!

**Comment by ftbb** [comment]
txs.  I will update readme.
