### ISSUE TITLE
How to configure a Proxy?

### ISSUE THREAD

**Issue by mikescannell** [symphonyoss/symphony-java-client#49]
Is there a simple way to pass proxy settings into the client for calls? This is a popular ask with the clients.

**Comment by pmonks** [comment]
IIRC issue #15 goes into some detail on this.

**Comment by ftbb** [comment]
Please see issue #15 

Use CustomHttpClient (bundled with SJC) with ClientConfig configured for proxy access. 

Using Jersey.

     ...
     ClientConfig config = new ClientConfig();
     config.connectorProvider(new ApacheConnectorProvider());  //You might need to change this
     config.property(ClientProperties.PROXY_URI, proxy);
     config.property(ClientProperties.PROXY_USERNAME,user);
     config.property(ClientProperties.PROXY_PASSWORD,pass);
     Client client =  CustomHttpClient.getClient(clientKeyStore, clientKeyStorePass, trustStore, trustStorePass, config);

     symClient.setDefaultHttpClient(client);
     symClient.init();
     ...

Please close if satisfied with response.

**Comment by mikescannell** [comment]
Thanks!

**Comment by arkadiyk** [comment]
One more trick to get the proxy working. You need to add the `client` as a last param into AuthorizationClient constructor:
```java
        AuthorizationClient authClient = new AuthorizationClient(
                initParams.get("sessionauth.url"),
                initParams.get("keyauth.url"),
                client);
```

**Comment by ftbb** [comment]
Great point and reminds me in 1.0.1 to simplify init of client removing the need to instantiate the AuthorizationClient.  The current SymphonyBasicClient already refreshes session tokens which means it has all the logic to perform the actions.

**Comment by ftbb** [comment]
Also realized this was already documented in the wiki:

 https://github.com/symphonyoss/symphony-java-client/wiki/Creating-a-session#using-a-custom-http-client
