### ISSUE TITLE
Add "list" endpoint to StreamsClient

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#50]
It would be great if the [StreamsClient](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/symphony/clients/StreamsClient.java) included support for the `/v1/streams/list` REST endpoint, as this is a good way for a bot to list out which streams it's already participating in.

**Comment by ftbb** [comment]
commit 9667ab4883a95a87afae5208617eebf47813bda9

It was a pain..

Also check out new example at:  https://github.com/symphonyoss/symphony-java-sample-bots/tree/develop/src/main/java/org/symphonyoss/examples/streams

**Comment by pmonks** [comment]
This is working great for me in 1.0.2-SNAPSHOT.  Thanks @ftbb!
