### ISSUE TITLE
Read DataFeed API allows a "maxMessages" query parameter

### ISSUE THREAD

**Issue by shirleyshan** [symphonyoss/symphony-java-client#51]
DataFeedClientImpl.getMessagesFromDatafeed method defaults the "maxMessages" to 100. Please allow this value to be passed in instead of being fixed at 100.

**Comment by ftbb** [comment]
I'm happy to change this, but are you calling DataFeedClientImpl.getMessagesFromDatafeed directly or using Services (ChatService, RoomService)  that are underpinned by the MessageService?

**Comment by ftbb** [comment]
commit 3e23ed251947e93391de03adde1caf38adb83569

-Added method: getMessagesFromDatafeed(Datafeed, MaxMessages)
-If you want to change the default number of messages (100) for existing Services, set the system property "datafeed.max.messages"

1.0.2-SNAPSHOT published
