### ISSUE TITLE
1.0.2-SNAPSHOT changes to JVM environment variables

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#56]
Updating [symphony-java-sample-bots](https://github.com/symphonyoss/symphony-java-sample-bots) from `1.0.1` to `1.0.2-SNAPSHOT`, testing broke due to the following JVM variable name changes - https://github.com/symphonyoss/symphony-java-sample-bots/commit/6883e2621b221a1c6aeeea77df471ab6397d1fa7

This means that all existing bots that upgrade to the new version would break.

Not sure what's the best course of actions to advise, but options are:
- Document on the README and socialise on dev@symphony.foundation the change
- Release a 2.x version

**Comment by ftbb** [comment]
Not too sure I understand the issue here.  

I have just updated external samples project with the latest SNAPSHOT and all seems to be working fine.  Can you please check and verify again.
