### ISSUE TITLE
org.symphonyoss.client.exceptions.StreamsException: Failed to retrieve stream for given user ids...

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#57]
The symphony-java-sample-bots are currently failing with the exception reported on https://travis-ci.org/symphonyoss/symphony-java-sample-bots/builds/247470557#L2085

Source code of the test can be found on https://github.com/symphonyoss/symphony-java-sample-bots/blob/develop/src/test/java/org/symphonyoss/simplebot/EchoBotIT.java

I believe this issue was introduced with the rollout of Symphony API 1.46 , but not sure how to fix it.

**Comment by ftbb** [comment]
With latest SNAPSHOT all seems to be working, so please check and close.

**Comment by ftbb** [comment]
No update here and tested multiple times.
