### ISSUE TITLE
Bug spotted by WhiteSource

### ISSUE THREAD

**Issue by maoo** [symphonyoss/symphony-java-client#58]
One of the transitive dependencies fetched by Maven is Javassist 3.18.1-GA, which is affected by https://jira.jboss.org/browse/JASSIST-227

Updating to version 3.21.0-GA fixes the issue (check commit applied to symphony-java-sample-bots) - https://github.com/symphonyoss/symphony-java-sample-bots/commit/cb7c67637aa4f1df361c6cc203c44389ccc51259

**Comment by ftbb** [comment]
Updated dependencies on both SJC and symphony-java-api 1.47.1-SNAPSHOT.

commit d95f444ac0a423adb8381fde15f4efc2fda36842
