### ISSUE TITLE
Support For JWT Authorization Endpoint?

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-java-client#63]
It would be nice if the Symphony Client module also supported Symphony's JWT auth mechanism, the endpoint being here:

/sessionauth/v1/authenticate/extensionApp

This is described in some detail here:  https://extension-api.symphony.com/docs/application-authentication

However, the Symphony Client would just need to serve up the extensionApp point I think.

**Comment by ftbb** [comment]
commit 3dede96dff0d7bef4838a2035548b82515299fe1

See example:  https://github.com/symphonyoss/symphony-java-client/blob/develop/examples/extensionappauth/ExtensionAppAuthentication.java

If satisfied, close issue.

**Comment by robmoffat** [comment]
Great work, thanks Frank!
