### ISSUE TITLE
Access to PodApi

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-java-client#66]
Is there a way to get access to the PodAPI via the SymphonyClient object?

It doesn't seem there is.  Can the use of this be wrapped into AuthenticationClient, in the same way as SymExtensionAppAuth is?

Otherwise, I have to jump through hoops to create the ApiClient class, and build my own:

```java
ApiClient apiClient = org.symphonyoss.symphony.authenticator.invoker.Configuration.getDefaultApiClient();
        apiClient.setHttpClient(httpClient);
        apiClient.setBasePath(sessionauthUrl);
 PodApi podApi = new PodApi(apiClient);
        PodCertificate certificate = podApi.v1AppPodCertificateGet();
```

Not critical, just an idea.

thanks,
Rob

**Comment by ftbb** [comment]
At this stage the SJC only exposes the services and clients that implement the underlying REST API (language binding).   The idea was to hide that complexity and potential underlying changes (models, messaging, apiclient..etc) that could impact the developer.  

Exposing the underlying ApiClient(s) (pod,agent,auth..) is something to consider, but again not the original design pattern of the project.  

Just to point out, the underlying language binding (Jersey2 Client) is managed in a separate project ( https://github.com/symphonyoss/symphony-java-api ) which you can use directly by implementing:

   <dependency>
            <groupId>org.symphonyoss.symphony</groupId>
            <artifactId>symphony-authenticator-java-jersey2-client</artifactId>
            <version>${symphony-api-version}</version>
        </dependency>
        <dependency>
            <groupId>org.symphonyoss.symphony</groupId>
            <artifactId>symphony-agent-java-jersey2-client</artifactId>
            <version>${symphony-api-version}</version>
        </dependency>
        <dependency>
            <groupId>org.symphonyoss.symphony</groupId>
            <artifactId>symphony-pod-java-jersey2-client</artifactId>
            <version>${symphony-api-version}</version>
        </dependency>

**Comment by robmoffat** [comment]
Well, /v1/app/pod/certificate is an endpoint exposed in the REST API, so by that logic it should expose it, no?  

Or is there another way to access this endpoint that I didn't see?

**Comment by ftbb** [comment]
Messy...but for now you can simply instantiate an ApiClient from the language binding and use the authorization tokens from the initialized SymphonyClient if needed.  All manual here...but based on your example.  (Note:  I will add this call to an existing SJC client soon..most likely the AuthenticationClient.getPodCertificate()) 
        
        ApiClient apiClient = org.symphonyoss.symphony.authenticator.invoker.Configuration.getDefaultApiClient();
        
        //You should be able to get AgentUrl from SymphonyConfig... 
        apiClient.setBasePath(symphonyConfig.get(SymphonyClientConfigID.POD_URL)); 
          
         //instantiate an API with the client..
          PodApi podApi = new PodApi(apiClient);

          PodCertificate podCertificate= podApi.v1AppPodCertificateGet();

**Comment by ftbb** [comment]
commit 991458c97666da81233a1813f3f30507527ef2fd

New class called SymphonyApis, which you can access through the SymphonyClient instance.

Again, this is not something recommended in the end.
