### ISSUE TITLE
Newline characters stripped from message

### ISSUE THREAD

**Issue by bmcd87** [symphonyoss/symphony-java-client#70]
If you type "first*SHIFT+ENTER*second" to write on multiple lines, it shows up properly in the symphony chat room as:
User: first
second

But when you receive the SymMessage in the java client, the message no longer has any whitespace character (newline or otherwise) at all:
<messageML>firstsecond</messageML>

Is this a known issue with the symphony api?

Thanks

**Comment by ftbb** [comment]
Just tested.. (AgentServer 1.46.3)
That seems to be a bug on the Symphony side as a new line should translate into a break </br>, which is not coming through on the PresentationML from the Datafeed events. 

Will raise it..

**Comment by bmcd87** [comment]
Thanks!

**Comment by ftbb** [comment]
This issue was reproduced by Symphony support teams and registered.

**Comment by bmcd87** [comment]
@ftbb Hey, I don't want to reopen this issue or anything since I know it's not a bug in this component, but I was curious if you could tell me where I could track this issue or who to reach out to to find out the status of the fix. Thanks!
