### ISSUE TITLE
Rename MessageFeedWorker

### ISSUE THREAD

**Issue by dferguson992** [symphonyoss/symphony-java-client#75]
Rename MessageFeedWorker to DatafeedWorker.  It has a DataFeedListener object within it and it's use is associated with datafeeds, not message feeds.

**Comment by ftbb** [comment]
True...  

When originally created was thinking more about messages than events and focus on MessageService -> MessageFeedWorker.   

Happy to change this as there is no impact to end users..

**Comment by ftbb** [comment]
commit 8efb28e10dbd1c56e1bbef0376083b8d43ba26f1
