### ISSUE TITLE
Make MessageFeedWorker public

### ISSUE THREAD

**Issue by dferguson992** [symphonyoss/symphony-java-client#76]
Change MessageFeedWorker's access level to public.  Otherwise no one can use it.

**Comment by ftbb** [comment]
Similar to issue #77 , the intention was never to make these workers public as they underpin Services.  The concept of "Services" is to abstract away all the underlying work a developer needs to handle in terms of eventing and classification to allow more focus on use cases.  

At this point in time, the closest you can get to a firehose of messages is attaching a "MessageListener" to the "MessageService".   

**One addition would be to add another listener for raw <SymEvent>, which would basically cover all uses cases and again eliminate the need to expose underlying workers. 

As always, the developer has many options with SJC.  They can always use the "Client" interfaces to create their own services, workers, SymphonyClient even..etc..  In fact, they always have access to the generated language bindings in the end (not recommended) as a last resort (reflection on ftbb not keeping up).
