### ISSUE TITLE
Make DataFeedListener public

### ISSUE THREAD

**Issue by dferguson992** [symphonyoss/symphony-java-client#77]
Change DataFeedWorker's access level to public.  Otherwise no one can use it.

**Comment by ftbb** [comment]
Never intended to be public as it should only be accessible via "Services".  

Services hide away all the underlying event management and expose higher level functions. 

Datafeed underpins the "MessageService" that underpins all other services.  see:  https://github.com/symphonyoss/symphony-java-client/wiki/Overview

A user always has the ability to create their own datafeed implementation and event management utilizing the client interfaces.  With this said, they would probably be reproducing the wheel in the end when it comes to satisfying the most common use cases that the existing "Services" already provide.
