### ISSUE TITLE
V4 Support for DataFeedClient

### ISSUE THREAD

**Issue by dferguson992** [symphonyoss/symphony-java-client#78]
With V4 endpoints being the latest and greatest, the datafeed should support V4 endpoints.  At this point, all methods in the DataFeedClientImpl that aren't deprecated throw "NotSupportedExceptions."  It would seem this is because there is no V4 support in the DataFeedClient.

To use the DataFeedClientImpl at this time, you must use deprecated methods that require V1 APIs to use them.  If you generate your client with a V4 API, you will get a "NotSupportedException."  This severely limits the growth of the platform, preventing anyone who wants to use V4 endpoints from using a Datafeed.

**Comment by ftbb** [comment]
Would rather remove all V2 support from impl...if that's OK with you?

In fact, the intention of 1.1.0 was to remove all V2.

With that said, I think in the future exceptions should be generated for version compatibility.

**Comment by dnsymphony** [comment]
You could call Agent's health check to determine Agent version and conditionally throw unsupported.

**Comment by ftbb** [comment]
This is a great point and something I'm trying to implement soon. 

Looking at adding in a "SystemClient" which will support the HealthChecks, version check and  Logout.

**Comment by dnsymphony** [comment]
Make sure you check Agent separately from the pod since Agent isn't necessarily in sync for on-prem deployments. In fact, it is often behind by a version or two.

**Comment by ftbb** [comment]
Implemented in 1.1.0
