### ISSUE TITLE
Exception causes Bot to stop functioning

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-java-client#80]
Hi Frank,

I've just seen this message in our logs:

> 09/10/201711:22:05.000 | 2017-10-09 11:22:05,692 ERROR [Thread-5][] c.h.g.s.b.ResearchBot - Unexpected exception. javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset 	at 
> org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287) 	at 
> org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252) 	at 
> org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684) 	at 
> org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681) 	at 
> org.glassfish.jersey.internal.Errors.process(Errors.java:315) 	at 
> org.glassfish.jersey.internal.Errors.process(Errors.java:297) 	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) 	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681) 	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411) 	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311) 	at org.symphonyoss.symphony.pod.invoker.ApiClient.invokeAPI(ApiClient.java:671) 	at org.symphonyoss.symphony.pod.api.StreamsApi.v1StreamsSidInfoGet(StreamsApi.java:560) 	at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.getStreamAttributes(StreamsClientImpl.java:391) 	at com.hsbc.gbm.symphony.bot.ResearchBot.isOneToOneChat(ResearchBot.java:126) 	at com.hsbc.gbm.symphony.bot.ResearchBot.onChatMessage(ResearchBot.java:92) 	at com.hsbc.gbm.symphony.bot.ResearchBot.lambda$new$0(ResearchBot.java:57) 	at org.symphonyoss.client.services.MessageService.onEvent(MessageService.java:260) 	at java.util.ArrayList.forEach(ArrayList.java:1249) 	at org.symphonyoss.client.services.MessageFeedWorker.readDatafeed(MessageFeedWorker.java:147) 	at org.symphonyoss.client.services.MessageFeedWorker.run(MessageFeedWorker.java:80) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.net.SocketException: Connection reset 	at java.net.SocketInputStream.read(SocketInputStream.java:209) 	at java.net.SocketInputStream.read(SocketInputStream.java:141) 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) 	at sun.security.ssl.InputRecord.read(InputRecord.java:503) 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) 	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394) 	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285) 	... 21 common frames omittedCollapse
> -- | --

Unfortunately, this seems to stop the Bot from working, as this exception isn't caught in `readDatafeed()`:

```java
   /**
     * Reads in raw messages from {@link org.symphonyoss.symphony.clients.DataFeedClient} and publishes out through
     * {@link DataFeedListener}
     */
    private void readDatafeed() {

        try {


            List<SymEvent> symEvents = symClient.getDataFeedClient().getEventsFromDatafeed(datafeed);

            if (symEvents != null) {

                symEvents.forEach(dataFeedListener::onEvent);

            }


        } catch (DataFeedException e) {
            logger.error("Failed to create read datafeed from pod, please check connection..resetting.", e);
            datafeed = null;

        }

    }
```

It only catches `DataFeedException`, but it would be better to catch *everything* I think.  That, way, in this code in `MessageDataFeed`, the while loop would come into play:

```java
 @Override
    public void run() {


        //noinspection InfiniteLoopStatement
        while (!shutdown) {

                //Make sure its active
                initDatafeed();

                //Poll it
                readDatafeed();


        }

    }
```

**Comment by ftbb** [comment]
commit 8efb28e10dbd1c56e1bbef0376083b8d43ba26f1

Doing a catch all now, because you are seeing a Runtime exception which isn't be caught. 

Note: In the next few commits you should see a new way of receiving callbacks from underlying errors. Stay tuned.
