### ISSUE TITLE
Non-daemon thread somewhere

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#85]
Somewhere in SJC (since at least v1.0.2) a thread is being created that's not a daemon thread (I _suspect_ it's the thread that handles the data feed, but I haven't verified this).  As a result the JVM won't terminate when the default `main` thread terminates, leaving bot processes hanging.

**Comment by ftbb** [comment]
It is the DataFeedWorker (in 1.0.2 version MessageFeedWorker) thread.  

You have to call SymphonyClient.shutdown() to terminate.

Will look into handling this more gracefully..

**Comment by pmonks** [comment]
Would it make sense to set the thread to be a [daemon](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#setDaemon-boolean-)?  Or does that leak resources somewhere?

**Comment by dovie** [comment]
In addition to the problems with deamon-ness, is simply identifying the thread. I've submitted PR #88  to address the latter issue so we have a better understanding of SymClient-spawned threads.

**Comment by ftbb** [comment]
Thanks @dovie.  Also added to new PresenceWorker..

Going to close this, but happy to reopen if we are seeing issues.
