### ISSUE TITLE
Additional ctor for SymphonyClientConfig

### ISSUE THREAD

**Issue by dferguson992** [symphonyoss/symphony-java-client#92]
Inspired by #91 

What about a constructor for the SymphonyClientConfig object that takes a string location for the properties file and calls the load method with that file location in mind.  

`
public SymphonyClientConfig(String configFile) {
     this.set(SymphonyClientConfigID.SYMPHONY_CONFIG_FILE, configFile);
     load();
}
`

**Comment by ftbb** [comment]
commit 6779a9ebaa68b8bd93dcf918b3832738d76e933d

Done
