### ISSUE TITLE
SymphonyClientConfig set(String, String)

### ISSUE THREAD

**Issue by dferguson992** [symphonyoss/symphony-java-client#93]
The SymphonyClientConfig is a great way to externalize and abstract a lot of the required properties needed by a client.  Would be good if a "set" method was added to the class that allowed users to set additional properties needed by their applications (i.e. an fixed stream id to post messages to, etc.).  Could look like the following:

`public void set(String id, String value) {
		config.setProperty(id, value);
	}`

**Comment by ftbb** [comment]
commit 4385b6c3e2bb47cb54291360ccdb721cf1cd4ec2

New getters / setters and also upsert(propertiesFile) which will update/insert additional properties files into active config. 

Note:  getters will continue to search  in this order 1) properties config in class 2) system property 3) environment variable (converts "." to "_" and makes property uppercase)
