### ISSUE TITLE
SymphonyClientConfig should use the Builder pattern

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#97]
With the older `init` methods now deprecated ([1](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/client/SymphonyClient.java#L56), [2](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/client/SymphonyClient.java#L68), [3](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/client/SymphonyClient.java#L81)), indications are that the [`SymphonyClientConfig`](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/client/SymphonyClientConfig.java) and [`SymphonyClientConfigID`](https://github.com/symphonyoss/symphony-java-client/blob/master/symphony-client/src/main/java/org/symphonyoss/client/SymphonyClientConfigID.java) classes are, or will become, the only supported way to initialise Symphony Java Client.

These classes appear to have been introduced to confront the (legitimate!) problem of proliferating constructors with lengthy parameter sets (aka the "telescoping constructor anti-pattern"), however the current solution is at odds with [longstanding Java best practice in this area](https://www.amazon.com/Effective-Java-3rd-Joshua-Bloch/dp/0134685997); i.e. application of the [Builder pattern](https://en.wikipedia.org/wiki/Builder_pattern).  This makes SJC harder to instantiate in many downstream environments (notably those where dependency injection is in use).

It would be preferable if SJC adopted Java best practice here and introduced the Builder pattern, ideally the [Step Builder variant](https://rdafbn.blogspot.ie/2012/07/step-builder-pattern_28.html).

**Comment by ftbb** [comment]
I agree and was always in the TODO bucket.  Will be in the next release.

**Comment by pmonks** [comment]
@ftbb oh nice!  I already started work on a fix - should I stop?

**Comment by pmonks** [comment]
[I believe this can be closed?](https://github.com/symphonyoss/symphony-java-client/blob/symphony-java-client-1.1.4/symphony-client/src/main/java/org/symphonyoss/client/SymphonyClientConfigBuilder.java)
